name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos_big_sur:
    runs-on: macos-11

    strategy:
      matrix:
        xcode:
          - "13.2"

    name: "macOS Big Sur (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          make
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
